# Climate mortality and hospital admission data



[dataset](https://www.ons.gov.uk/peoplepopulationandcommunity/birthsdeathsandmarriages/deaths/datasets/climaterelatedmortalityandhospitaladmissionsenglandandwales)

In [2]:
import polars as pl
import polars.selectors as cs
import plotly.express as px
import fsspec
import fastexcel
from loguru import logger

In [3]:
def read_excel_tables(url) -> fastexcel.ExcelReader:
    with fsspec.open(url) as file:
        logger.info(f"reading excell file from {url}")
        reader = fastexcel.read_excel(file.read())
    logger.info(f"file contains the sheets: {reader.sheet_names}")
    return reader

reader = read_excel_tables("https://assets.publishing.service.gov.uk/media/67ebd7ade9c76fa33048c592/heat-mortality-monitoring-data-2024.ods")

2026-05-05 15:39:57.750 | INFO     | __main__:read_excel_tables:3 - reading excell file from https://assets.publishing.service.gov.uk/media/67ebd7ade9c76fa33048c592/heat-mortality-monitoring-data-2024.ods
2026-05-05 15:39:57.776 | INFO     | __main__:read_excel_tables:5 - file contains the sheets: ['Cover', 'Contents', 'Notes', 'Table_1', 'Table_2', 'Table_3', 'Table_4', 'Table_5', 'Table_6', 'Table_7', 'Table_8', 'Table_9']

In [13]:
description = reader.load_sheet('Cover').to_polars().select(cs.all().str.join(delimiter="\n")).item(0,0)
description

'Description\nUKHSA heat mortality monitoring reports provide information on deaths observed during heat episodes each year in England, to inform public health action.\nThe report on summer 2024 includes estimates of observed heat-associated mortality and years of life lost, broken down by demographics, cause of death and place of death. In addition, it compares observed mortality with modelled predictions, based on the temperature-mortality relationship in previous summers.\nOur statistical practice is regulated by the Office for Statistics Regulation (OSR). The OSR sets the standards of trustworthiness, quality and value in the Code of Practice for Statistics that all producers of Official Statistics should adhere to.\nContact information\nExtreme Events and Health Protection Team\nCentre for Climate and Health Security\nUK Health Security Agency\nextremeevents@ukhsa.gov.uk\nPublication date\nRelease date: 3 April 2025'

In [17]:
reader.load_sheet('Table_1', header_row=3).to_polars()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Heat      ┆ Heat      ┆ Heat      ┆ Heat-asso ┆ … ┆ Upper 95% ┆ Heat-asso ┆ Lower 95% ┆ Upper    │
│ episode   ┆ episode   ┆ episode   ┆ ciated    ┆   ┆ confidenc ┆ ciated    ┆ confidenc ┆ 95% conf │
│ ---       ┆ start     ┆ end date  ┆ deaths    ┆   ┆ e         ┆ deaths    ┆ e         ┆ idence   │
│ str       ┆ date      ┆ ---       ┆ estimat…  ┆   ┆ interval  ┆ per hea…  ┆ interval  ┆ interval │
│           ┆ ---       ┆ str       ┆ ---       ┆   ┆ …         ┆ ---       ┆ …         ┆ …        │
│           ┆ str       ┆           ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Episode 1 ┆ 24 June   ┆ 27 June   ┆ 394.0     ┆ … ┆ 603.0     ┆ 98.0      ┆ 46.0      ┆ 151.0    │
│           ┆ 2024      ┆ 2024      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Episode 2 ┆ 18 July   ┆ 20 July   ┆ 467.0     ┆ … ┆ 646.0     ┆ 156.0     ┆ 96.0      ┆ 215.0    │
│           ┆ 2024      ┆ 2024      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Episode 3 ┆ 30 July   ┆ 2 August  ┆ 275.0     ┆ … ┆ 477.0     ┆ 69.0      ┆ 18.0      ┆ 119.0    │
│           ┆ 2024      ┆ 2024      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Episode 4 ┆ 11 August ┆ 13 August ┆ 142.0     ┆ … ┆ 312.0     ┆ 47.0      ┆ -9.0      ┆ 104.0    │
│           ┆ 2024      ┆ 2024      ┆           ┆   ┆           ┆           ┆           ┆          │
│ All       ┆ Multiple  ┆ Multiple  ┆ 1311.0    ┆ … ┆ 1692.0    ┆ 94.0      ┆ 66.0      ┆ 121.0    │
│ episodes  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ combined  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [18]:
reader.load_sheet('Table_2', header_row=3).to_polars()

shape: (45, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Region    ┆ Heat      ┆ Heat      ┆ Heat      ┆ … ┆ Upper 95% ┆ Heat-asso ┆ Lower 95% ┆ Upper    │
│ ---       ┆ episode   ┆ episode   ┆ episode   ┆   ┆ confidenc ┆ ciated    ┆ confidenc ┆ 95% conf │
│ str       ┆ ---       ┆ start     ┆ end date  ┆   ┆ e         ┆ deaths    ┆ e         ┆ idence   │
│           ┆ str       ┆ date      ┆ ---       ┆   ┆ interval  ┆ per mil…  ┆ interval  ┆ interval │
│           ┆           ┆ ---       ┆ str       ┆   ┆ …         ┆ ---       ┆ …         ┆ …        │
│           ┆           ┆ str       ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ North     ┆ Episode 1 ┆ 24 June   ┆ 27 June   ┆ … ┆ 71.0      ┆ 8.0       ┆ -10.0     ┆ 26.0     │
│ East      ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ North     ┆ Episode 2 ┆ 18 July   ┆ 20 July   ┆ … ┆ 77.0      ┆ 13.0      ┆ -3.0      ┆ 28.0     │
│ East      ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ North     ┆ Episode 3 ┆ 30 July   ┆ 2 August  ┆ … ┆ 46.0      ┆ 0.0       ┆ -17.0     ┆ 17.0     │
│ East      ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ North     ┆ Episode 4 ┆ 11 August ┆ 13 August ┆ … ┆ 45.0      ┆ 2.0       ┆ -13.0     ┆ 17.0     │
│ East      ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ North     ┆ All       ┆ Multiple  ┆ Multiple  ┆ … ┆ 152.0     ┆ 23.0      ┆ -10.0     ┆ 56.0     │
│ East      ┆ episodes  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ combined  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ South     ┆ Episode 1 ┆ 24 June   ┆ 27 June   ┆ … ┆ 137.0     ┆ 11.0      ┆ -1.0      ┆ 24.0     │
│ West      ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ South     ┆ Episode 2 ┆ 18 July   ┆ 20 July   ┆ … ┆ 124.0     ┆ 11.0      ┆ 0.0       ┆ 21.0     │
│ West      ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ South     ┆ Episode 3 ┆ 30 July   ┆ 2 August  ┆ … ┆ 111.0     ┆ 7.0       ┆ -5.0      ┆ 19.0     │
│ West      ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ South     ┆ Episode 4 ┆ 11 August ┆ 13 August ┆ … ┆ 70.0      ┆ 2.0       ┆ -8.0      ┆ 12.0     │
│ West      ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ South     ┆ All       ┆ Multiple  ┆ Multiple  ┆ … ┆ 316.0     ┆ 32.0      ┆ 10.0      ┆ 54.0     │
│ West      ┆ episodes  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ combined  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [20]:
reader.load_sheet('Table_4', header_row=3).to_polars()

shape: (30, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Age group ┆ Heat      ┆ Heat      ┆ Heat      ┆ … ┆ Upper 95% ┆ Heat-asso ┆ Lower 95% ┆ Upper    │
│ ---       ┆ episode   ┆ episode   ┆ episode   ┆   ┆ confidenc ┆ ciated    ┆ confidenc ┆ 95% conf │
│ str       ┆ ---       ┆ start     ┆ end date  ┆   ┆ e         ┆ deaths    ┆ e         ┆ idence   │
│           ┆ str       ┆ date      ┆ ---       ┆   ┆ interval  ┆ per mil…  ┆ interval  ┆ interval │
│           ┆           ┆ ---       ┆ str       ┆   ┆ …         ┆ ---       ┆ …         ┆ …        │
│           ┆           ┆ str       ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0 to 24   ┆ Episode 1 ┆ 24 June   ┆ 27 June   ┆ … ┆ 27.0      ┆ 0.0       ┆ -1.0      ┆ 2.0      │
│ years     ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ 0 to 24   ┆ Episode 2 ┆ 18 July   ┆ 20 July   ┆ … ┆ 19.0      ┆ 0.0       ┆ -1.0      ┆ 1.0      │
│ years     ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ 0 to 24   ┆ Episode 3 ┆ 30 July   ┆ 2 August  ┆ … ┆ 32.0      ┆ 1.0       ┆ -1.0      ┆ 2.0      │
│ years     ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ 0 to 24   ┆ Episode 4 ┆ 11 August ┆ 13 August ┆ … ┆ 15.0      ┆ 0.0       ┆ -1.0      ┆ 1.0      │
│ years     ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ 0 to 24   ┆ All       ┆ Multiple  ┆ Multiple  ┆ … ┆ 57.0      ┆ 1.0       ┆ -1.0      ┆ 3.0      │
│ years     ┆ episodes  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ combined  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 85 years  ┆ Episode 1 ┆ 24 June   ┆ 27 June   ┆ … ┆ 347.0     ┆ 148.0     ┆ 56.0      ┆ 240.0    │
│ and over  ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ 85 years  ┆ Episode 2 ┆ 18 July   ┆ 20 July   ┆ … ┆ 350.0     ┆ 164.0     ┆ 85.0      ┆ 242.0    │
│ and over  ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ 85 years  ┆ Episode 3 ┆ 30 July   ┆ 2 August  ┆ … ┆ 302.0     ┆ 120.0     ┆ 31.0      ┆ 209.0    │
│ and over  ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ 85 years  ┆ Episode 4 ┆ 11 August ┆ 13 August ┆ … ┆ 224.0     ┆ 80.0      ┆ 5.0       ┆ 155.0    │
│ and over  ┆           ┆ 2024      ┆ 2024      ┆   ┆           ┆           ┆           ┆          │
│ 85 years  ┆ All       ┆ Multiple  ┆ Multiple  ┆ … ┆ 996.0     ┆ 521.0     ┆ 353.0     ┆ 688.0    │
│ and over  ┆ episodes  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ combined  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
reader.load_sheet('Table_5', header_row=3).to_polars()

shape: (10, 10)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Sex    ┆ Heat       ┆ Heat       ┆ Heat      ┆ … ┆ Upper 95% ┆ Heat-asso ┆ Lower 95% ┆ Upper 95% │
│ ---    ┆ episode    ┆ episode    ┆ episode   ┆   ┆ confidenc ┆ ciated    ┆ confidenc ┆ confidenc │
│ str    ┆ ---        ┆ start date ┆ end date  ┆   ┆ e         ┆ deaths    ┆ e         ┆ e         │
│        ┆ str        ┆ ---        ┆ ---       ┆   ┆ interval  ┆ per mil…  ┆ interval  ┆ interval  │
│        ┆            ┆ str        ┆ str       ┆   ┆ …         ┆ ---       ┆ …         ┆ …         │
│        ┆            ┆            ┆           ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---       │
│        ┆            ┆            ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Female ┆ Episode 1  ┆ 24 June    ┆ 27 June   ┆ … ┆ 326.0     ┆ 6.0       ┆ 1.0       ┆ 11.0      │
│        ┆            ┆ 2024       ┆ 2024      ┆   ┆           ┆           ┆           ┆           │
│ Female ┆ Episode 2  ┆ 18 July    ┆ 20 July   ┆ … ┆ 363.0     ┆ 8.0       ┆ 4.0       ┆ 12.0      │
│        ┆            ┆ 2024       ┆ 2024      ┆   ┆           ┆           ┆           ┆           │
│ Female ┆ Episode 3  ┆ 30 July    ┆ 2 August  ┆ … ┆ 273.0     ┆ 4.0       ┆ 0.0       ┆ 9.0       │
│        ┆            ┆ 2024       ┆ 2024      ┆   ┆           ┆           ┆           ┆           │
│ Female ┆ Episode 4  ┆ 11 August  ┆ 13 August ┆ … ┆ 237.0     ┆ 4.0       ┆ 0.0       ┆ 8.0       │
│        ┆            ┆ 2024       ┆ 2024      ┆   ┆           ┆           ┆           ┆           │
│ Female ┆ All        ┆ Multiple   ┆ Multiple  ┆ … ┆ 952.0     ┆ 23.0      ┆ 14.0      ┆ 32.0      │
│        ┆ episodes   ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ combined   ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│ Male   ┆ Episode 1  ┆ 24 June    ┆ 27 June   ┆ … ┆ 364.0     ┆ 8.0       ┆ 2.0       ┆ 13.0      │
│        ┆            ┆ 2024       ┆ 2024      ┆   ┆           ┆           ┆           ┆           │
│ Male   ┆ Episode 2  ┆ 18 July    ┆ 20 July   ┆ … ┆ 357.0     ┆ 8.0       ┆ 4.0       ┆ 13.0      │
│        ┆            ┆ 2024       ┆ 2024      ┆   ┆           ┆           ┆           ┆           │
│ Male   ┆ Episode 3  ┆ 30 July    ┆ 2 August  ┆ … ┆ 289.0     ┆ 5.0       ┆ 0.0       ┆ 10.0      │
│        ┆            ┆ 2024       ┆ 2024      ┆   ┆           ┆           ┆           ┆           │
│ Male   ┆ Episode 4  ┆ 11 August  ┆ 13 August ┆ … ┆ 146.0     ┆ 1.0       ┆ -3.0      ┆ 5.0       │
│        ┆            ┆ 2024       ┆ 2024      ┆   ┆           ┆           ┆           ┆           │
│ Male   ┆ All        ┆ Multiple   ┆ Multiple  ┆ … ┆ 899.0     ┆ 22.0      ┆ 13.0      ┆ 32.0      │
│        ┆ episodes   ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
│        ┆ combined   ┆            ┆           ┆   ┆           ┆           ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
from pydantic import BaseModel, HttpUrl

class HeatMortalityReader(BaseModel):
    url: HttpUrl

reader = read_excel_tables("https://assets.publishing.service.gov.uk/media/69ca6b8476f83be521bb3d30/heat-mortality-monitoring-report-England-2025-data.ods")

2026-05-05 15:52:12.465 | INFO     | __main__:read_excel_tables:3 - reading excell file from https://assets.publishing.service.gov.uk/media/69ca6b8476f83be521bb3d30/heat-mortality-monitoring-report-England-2025-data.ods
2026-05-05 15:52:12.478 | INFO     | __main__:read_excel_tables:5 - file contains the sheets: ['Cover', 'Contents', 'Notes', 'Table_1', 'Table_2', 'Table_3', 'Table_4', 'Table_5', 'Table_6', 'Table_7', 'Table_8', 'Table_9']

In [25]:
reader = read_excel_tables("https://assets.publishing.service.gov.uk/media/69ca6b8476f83be521bb3d30/heat-mortality-monitoring-report-England-2025-data.ods")
reader.load_sheet("Table_1", header_row=3).to_polars()

2026-05-05 15:56:08.578 | INFO     | __main__:read_excel_tables:3 - reading excell file from https://assets.publishing.service.gov.uk/media/69ca6b8476f83be521bb3d30/heat-mortality-monitoring-report-England-2025-data.ods
2026-05-05 15:56:08.592 | INFO     | __main__:read_excel_tables:5 - file contains the sheets: ['Cover', 'Contents', 'Notes', 'Table_1', 'Table_2', 'Table_3', 'Table_4', 'Table_5', 'Table_6', 'Table_7', 'Table_8', 'Table_9']

shape: (6, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Heat      ┆ Heat      ┆ Heat      ┆ Heat-asso ┆ … ┆ Upper 95% ┆ Heat-asso ┆ Lower 95% ┆ Upper    │
│ episode   ┆ episode   ┆ episode   ┆ ciated    ┆   ┆ confidenc ┆ ciated    ┆ confidenc ┆ 95% conf │
│ ---       ┆ start     ┆ end date  ┆ deaths    ┆   ┆ e         ┆ deaths    ┆ e         ┆ idence   │
│ str       ┆ date      ┆ ---       ┆ estimat…  ┆   ┆ interval  ┆ per hea…  ┆ interval  ┆ interval │
│           ┆ ---       ┆ str       ┆ ---       ┆   ┆ …         ┆ ---       ┆ …         ┆ …        │
│           ┆ str       ┆           ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Episode 1 ┆ 19 June   ┆ 23 June   ┆ 253.0     ┆ … ┆ 470.0     ┆ 63.0      ┆ 9.0       ┆ 118.0    │
│           ┆ 2025      ┆ 2025      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Episode 2 ┆ 27 June   ┆ 2 July    ┆ 203.0     ┆ … ┆ 473.0     ┆ 34.0      ┆ -11.0     ┆ 79.0     │
│           ┆ 2025      ┆ 2025      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Episode 3 ┆ 9 July    ┆ 15 July   ┆ 203.0     ┆ … ┆ 495.0     ┆ 29.0      ┆ -13.0     ┆ 71.0     │
│           ┆ 2025      ┆ 2025      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Episode 4 ┆ 17 July   ┆ 19 July   ┆ 146.0     ┆ … ┆ 328.0     ┆ 49.0      ┆ -12.0     ┆ 109.0    │
│           ┆ 2025      ┆ 2025      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Episode 5 ┆ 10 August ┆ 16 August ┆ 697.0     ┆ … ┆ 993.0     ┆ 100.0     ┆ 57.0      ┆ 142.0    │
│           ┆ 2025      ┆ 2025      ┆           ┆   ┆           ┆           ┆           ┆          │
│ All       ┆ Multiple  ┆ Multiple  ┆ 1504.0    ┆ … ┆ 2072.0    ┆ 56.0      ┆ 35.0      ┆ 77.0     │
│ episodes  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ combined  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [26]:
reader = read_excel_tables("https://assets.publishing.service.gov.uk/media/67ebd7ade9c76fa33048c592/heat-mortality-monitoring-data-2024.ods")
reader.load_sheet("Table_1", header_row=3).to_polars()

2026-05-05 15:57:04.909 | INFO     | __main__:read_excel_tables:3 - reading excell file from https://assets.publishing.service.gov.uk/media/67ebd7ade9c76fa33048c592/heat-mortality-monitoring-data-2024.ods
2026-05-05 15:57:04.925 | INFO     | __main__:read_excel_tables:5 - file contains the sheets: ['Cover', 'Contents', 'Notes', 'Table_1', 'Table_2', 'Table_3', 'Table_4', 'Table_5', 'Table_6', 'Table_7', 'Table_8', 'Table_9']

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Heat      ┆ Heat      ┆ Heat      ┆ Heat-asso ┆ … ┆ Upper 95% ┆ Heat-asso ┆ Lower 95% ┆ Upper    │
│ episode   ┆ episode   ┆ episode   ┆ ciated    ┆   ┆ confidenc ┆ ciated    ┆ confidenc ┆ 95% conf │
│ ---       ┆ start     ┆ end date  ┆ deaths    ┆   ┆ e         ┆ deaths    ┆ e         ┆ idence   │
│ str       ┆ date      ┆ ---       ┆ estimat…  ┆   ┆ interval  ┆ per hea…  ┆ interval  ┆ interval │
│           ┆ ---       ┆ str       ┆ ---       ┆   ┆ …         ┆ ---       ┆ …         ┆ …        │
│           ┆ str       ┆           ┆ f64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Episode 1 ┆ 24 June   ┆ 27 June   ┆ 394.0     ┆ … ┆ 603.0     ┆ 98.0      ┆ 46.0      ┆ 151.0    │
│           ┆ 2024      ┆ 2024      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Episode 2 ┆ 18 July   ┆ 20 July   ┆ 467.0     ┆ … ┆ 646.0     ┆ 156.0     ┆ 96.0      ┆ 215.0    │
│           ┆ 2024      ┆ 2024      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Episode 3 ┆ 30 July   ┆ 2 August  ┆ 275.0     ┆ … ┆ 477.0     ┆ 69.0      ┆ 18.0      ┆ 119.0    │
│           ┆ 2024      ┆ 2024      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Episode 4 ┆ 11 August ┆ 13 August ┆ 142.0     ┆ … ┆ 312.0     ┆ 47.0      ┆ -9.0      ┆ 104.0    │
│           ┆ 2024      ┆ 2024      ┆           ┆   ┆           ┆           ┆           ┆          │
│ All       ┆ Multiple  ┆ Multiple  ┆ 1311.0    ┆ … ┆ 1692.0    ┆ 94.0      ┆ 66.0      ┆ 121.0    │
│ episodes  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ combined  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [30]:
reader.load_sheet("Contents", header_row=2).to_polars()["Sheet title"].to_list()

['Notes used in this workbook',
 'Table 1. Heat-associated deaths and deaths per day by heat episode, England, summer 2024',
 'Table 2. Heat-associated deaths and mortality rates by region and heat episode, England, summer 2024',
 'Table 3. Heat-associated deaths and mortality rates by local resilience forum area, England, summer 2024',
 'Table 4. Heat-associated deaths and mortality rates by age group and heat episode, England, summer 2024',
 'Table 5. Heat-associated deaths and mortality rates by sex and heat episode, England, summer 2024',
 'Table 6. Heat-associated deaths and percentages above baseline by place of death and heat episode, England, summer 2024',
 'Table 7. Heat-associated deaths and percentages above baseline by cause of death, England, summer 2024',
 'Table 8. Heat-associated years of life lost by age group and heat episode, England, summer 2024',
 'Table 9. Modelled heat-associated deaths by heat episode, England, summer 2024']

In [24]:
temperature_risk = reader.load_sheet('1a', header_row=4).to_polars().select(
    temperature="Temperature\nDegrees Celsius",
    relative_risk="England\nEstimated relative risk of mortality",
    ci_lower="England\n95% Lower confidence interval for relative risk",
    ci_upper="England\n95% Upper confidence interval for relative risk"
)
px.line(
    temperature_risk,
    x="temperature",
    y="relative_risk"
)

In [19]:
reader.load_sheet('1c', header_row=4).to_polars()

shape: (34, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ Temperature  ┆ Age 18 to   ┆ Age 18 to   ┆ Age 18 to   ┆ Age 65      ┆ Age 65      ┆ Age 65      │
│ Degrees      ┆ 64 years    ┆ 64 years    ┆ 64 years    ┆ years and   ┆ years and   ┆ years and   │
│ Celsius      ┆ Estimated   ┆ 95% Lower   ┆ 95% Upper   ┆ over        ┆ over        ┆ over        │
│ ---          ┆ r…          ┆ c…          ┆ c…          ┆ Estimate…   ┆ 95% Lowe…   ┆ 95% Uppe…   │
│ f64          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ -6.0         ┆ 1.42        ┆ 1.31        ┆ 1.56        ┆ 1.81        ┆ 1.67        ┆ 1.97        │
│ -5.0         ┆ 1.35        ┆ 1.26        ┆ 1.45        ┆ 1.68        ┆ 1.57        ┆ 1.8         │
│ -4.0         ┆ 1.29        ┆ 1.22        ┆ 1.37        ┆ 1.56        ┆ 1.47        ┆ 1.65        │
│ -3.0         ┆ 1.24        ┆ 1.19        ┆ 1.3         ┆ 1.47        ┆ 1.4         ┆ 1.54        │
│ -2.0         ┆ 1.2         ┆ 1.16        ┆ 1.24        ┆ 1.39        ┆ 1.33        ┆ 1.44        │
│ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ 23.0         ┆ 1.08        ┆ 1.02        ┆ 1.15        ┆ 1.17        ┆ 1.12        ┆ 1.22        │
│ 24.0         ┆ 1.11        ┆ 1.02        ┆ 1.21        ┆ 1.25        ┆ 1.17        ┆ 1.33        │
│ 25.0         ┆ 1.15        ┆ 1.02        ┆ 1.3         ┆ 1.35        ┆ 1.24        ┆ 1.47        │
│ 26.0         ┆ 1.2         ┆ 1.02        ┆ 1.41        ┆ 1.47        ┆ 1.31        ┆ 1.65        │
│ 27.0         ┆ 1.25        ┆ 1.02        ┆ 1.55        ┆ 1.62        ┆ 1.4         ┆ 1.87        │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [20]:
reader.load_sheet('1d', header_row=4).to_polars()

shape: (9, 5)
┌──────────────────────┬───────────────┬───────────────┬─────────────────────┬─────────────────────┐
│ English Region       ┆ Cold Related  ┆ Cold Related  ┆ Heat Related Deaths ┆ Heat Related Deaths │
│ ---                  ┆ Deaths        ┆ Deaths        ┆ Estimated …         ┆ Deaths per…         │
│ str                  ┆ Estimated …   ┆ Deaths per…   ┆ ---                 ┆ ---                 │
│                      ┆ ---           ┆ ---           ┆ f64                 ┆ f64                 │
│                      ┆ f64           ┆ f64           ┆                     ┆                     │
╞══════════════════════╪═══════════════╪═══════════════╪═════════════════════╪═════════════════════╡
│ East of England      ┆ 2900.0        ┆ 9.0           ┆ 1600.0              ┆ 5.0                 │
│ East Midlands        ┆ 1800.0        ┆ 7.0           ┆ 900.0               ┆ 4.0                 │
│ London               ┆ 3000.0        ┆ 7.0           ┆ 2200.0              ┆ 5.0                 │
│ North East           ┆ 1200.0        ┆ 9.0           ┆ 700.0               ┆ 5.0                 │
│ North West           ┆ 3200.0        ┆ 9.0           ┆ 800.0               ┆ 2.0                 │
│ South East           ┆ 3800.0        ┆ 8.0           ┆ 1900.0              ┆ 4.0                 │
│ South West           ┆ 2800.0        ┆ 10.0          ┆ 1100.0              ┆ 4.0                 │
│ West Midlands        ┆ 2400.0        ┆ 8.0           ┆ 1200.0              ┆ 4.0                 │
│ Yorkshire and the    ┆ 1800.0        ┆ 7.0           ┆ 900.0               ┆ 3.0                 │
│ Humber               ┆               ┆               ┆                     ┆                     │
└──────────────────────┴───────────────┴───────────────┴─────────────────────┴─────────────────────┘